### ISSUE TITLE
Potential update on python API to make quadruped work

### ISSUE THREAD

**Issue by lyuyiqi** [deepmind/mujoco_mpc#130]
Hi deepmind team, 

thank you for developing the tool which has helped a lot with my project. Recently I have been trying to use the python API to collect some data of Unitree GO1 robot automatically, but when I tried to open the simulator with task_flat.xml and task_id="Quadruped Flat" I got some error. Later I noticed that in ui_agent_test.py there are some tests about quadruped skipped by a comment 'asset import issue' and I realized this may be out of my scope. 

I'm wondering whether you have the plan to fix this recently. If not I will have to start earlier to collect data by hand.

---
### The error I encountered:

```
Traceback (most recent call last):
  File "/home/yiqi/mujoco_mpc/python/workspace/test.py", line 21, in <module>
    with get_agent(task_id="Quadruped Flat", model=model) as agent:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yiqi/mujoco_mpc/python/workspace/test.py", line 8, in get_agent
    return agent_lib.Agent(
           ^^^^^^^^^^^^^^^^
  File "/home/yiqi/miniconda3/envs/mujoco/lib/python3.11/site-packages/mujoco_mpc/agent.py", line 88, in __init__
    self.init(
  File "/home/yiqi/miniconda3/envs/mujoco/lib/python3.11/site-packages/mujoco_mpc/agent.py", line 149, in init
    self.stub.Init(init_request)
  File "/home/yiqi/miniconda3/envs/mujoco/lib/python3.11/site-packages/grpc/_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yiqi/miniconda3/envs/mujoco/lib/python3.11/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (48432719 vs. 41943040)"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50261 {created_time:"2023-06-23T22:13:33.713218965-04:00", grpc_status:8, grpc_message:"Received message larger than max (48432719 vs. 41943040)"}"
```

**Comment by nimrod-gileadi** [comment]
If you're building from source, you could try increasing the size passed to [SetMaxReceiveMessageSize](https://github.com/deepmind/mujoco_mpc/blob/60f1838/grpc/agent_server.cc#L50) in mujoco_mpc/grpc/agent_server.cc, or possibly set it to -1.
